name: CI

on:
  push:
    branches:
      - master
      - 'fix/**'
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Unit & Coverage Tests (Local)
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    env:
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      API_BASE_URL: http://localhost:8000

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage pytest pytest-asyncio

      - name: Set PYTHONPATH and .env
        run: |
          echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
          mv .env.example .env || true

      - name: Wait for Redis to be ready
        run: |
          for i in $(seq 1 20); do
            nc -z localhost 6379 && echo "Redis is up" && exit 0
            sleep 1
          done
          echo "Redis did not start in time" && exit 1

      - name: Run tests with coverage
        run: |
          coverage run -m pytest tests/
          coverage report
          coverage xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

  integration-test:
    name: Integration Tests (Online Service)
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest
    env:
      API_BASE_URL: https://miniurl.gr

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage pytest pytest-asyncio

      - name: Run integration tests
        run: |
          coverage run -m pytest tests/smoke
          coverage report
          coverage xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          file: ./coverage.xml
          flags: integration-tests
          name: codecov-integration
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}