name: CI

on:
  push:
    branches:
      - master
      - 'fix/**'
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Unit & Integration Tests (Local)
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U testuser"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage pytest pytest-asyncio responses faker

      - name: Wait for Redis to be ready
        run: |
          for i in $(seq 1 20); do
            nc -z localhost 6379 && echo "Redis is up" && exit 0
            sleep 1
          done
          echo "Redis did not start in time" && exit 1

      - name: Wait for PostgreSQL to be ready
        run: |
          for i in $(seq 1 20); do
            nc -z localhost 5432 && echo "Postgres is up" && exit 0
            sleep 1
          done
          echo "Postgres did not start in time" && exit 1

      - name: Run tests with coverage
        run: |
          coverage run -m pytest tests
          coverage report
          coverage xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}